// src/lib/components/SelectorList.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		children: Snippet;
	}

	const { children }: Props = $props();
</script>

<div class="selector-list">
	{@render children()}
</div>

<style>
	.selector-list {
		display: grid;
		gap: 1rem;
		grid-auto-rows: 96px;
		grid-template-columns: repeat(auto-fill, 96px);
		justify-content: center;
		margin: 0 auto;
		width: 100%;
	}
</style>

// src/components/selectors/SelectorList.tsx
import { Link } from 'react-router-dom';
import styled from 'styled-components';

const SelectorList = styled.div`
  display: grid;
  gap: 1rem;
  grid-auto-rows: 115px;
  grid-template-columns: repeat(auto-fill, 115px);
  justify-content: center;
  width: 100%;
`;

const SelectorListItem = styled(Link)`
  align-items: center;
  border: 1px solid var(--selector__border-color);
  border-radius: 50%;
  color: inherit;
  display: flex;
  justify-content: center;
  text-align: center;
  text-decoration: none;
  transition: background-color 0.1s ease-in-out;

  :hover,
  :focus {
    background-color: var(--selector__border-color);
    outline: none;
    text-decoration: none;
  }
`;

export { SelectorList, SelectorListItem };
