// src/components/Header.svelte
<script lang="ts">
	import cx from 'utils/cx';
	import findBook from 'utils/findBook';
	import Search from './icons/Search.svelte';

	interface Props {
		book?: string;
		chapter?: string;
		sticky?: boolean;
	}

	const { book: bookKey, chapter, sticky } = $props<Props>();

	let book = $derived(bookKey ? findBook(bookKey) : null);
	let classes = $derived(cx('container', { stuck: sticky }));
</script>

<div class={classes}>
	<h1 class="text-[32px] text">
		<div class="flex items-center justify-center">
			<a href="/">Bible</a>

			{#if book}
				<span class="mx-2">&gt;</span>
				<a class="book-name" href={`/${book.key}`}>{book.label}</a>
			{/if}

			{#if chapter}
				<span class="mx-2">&gt;</span>
				<span>{chapter}</span>
			{/if}
		</div>
	</h1>

	<div class="flex items-center justify-center">
		<a href="/search">
			<Search />
		</a>
	</div>
</div>

<style>
	.container {
		background-color: var(--neutral500);
		display: flex;
		font-weight: bold;
		justify-content: space-between;
		padding: 3px 1rem 0 1rem;
		width: 100%;

		&.stuck {
			position: sticky;
			top: 0;
			z-index: 10;
		}
	}

	@media screen and (max-width: 767px) {
		.book-name {
			max-width: 170px;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
		}
	}
</style>

// src/components/header/Header.tsx
import { CenterBox, FlexBox } from '@common/Box';
import { SearchIcon } from '@common/Icons';
import { UnstyledLink } from '@common/Unstyled';
import { useHeaderStateContext } from '@contexts/HeaderContext';
import styled, { css } from 'styled-components';

const HeaderContainer = styled(FlexBox)<{ isSticky?: boolean }>`
  background-color: var(--header__bg-color);
  color: var(--font-color);
  width: 100%;

  ${({ isSticky }) =>
    isSticky &&
    css`
      position: sticky;
      top: 0;
    `};

  @media screen and (max-width: 767px) {
    ${UnstyledLink} {
      max-width: 200px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
  }
`;

const Separator = styled.span`
  margin: 0 0.5rem;
`;

const SearchLink = styled(UnstyledLink)`
  display: flex;
`;

function Header() {
  /* -- Hooks -- */
  const header = useHeaderStateContext();

  /* -- Rendering -- */
  const bookEl = header.value && (
    <>
      <Separator>&gt;</Separator>{' '}
      <UnstyledLink data-testid="book" to={`/${header?.value}`}>
        {header?.label}
      </UnstyledLink>
    </>
  );

  const chapterEl = header?.chapter && (
    <>
      <Separator>&gt;</Separator> <span data-testid="chapter">{header.chapter}</span>
    </>
  );

  return (
    <HeaderContainer
      data-testid="header"
      isSticky={header.sticky}
      justifyContent="space-between"
      px={3}
    >
      <h1>
        <CenterBox>
          <UnstyledLink to="/">Bible</UnstyledLink> {bookEl} {chapterEl}
        </CenterBox>
      </h1>

      <CenterBox>
        <SearchLink aria-label="Search" to="/search">
          <SearchIcon />
        </SearchLink>
      </CenterBox>
    </HeaderContainer>
  );
}

export default Header;
