// src/components/scrollers/ScrollUp.tsx
import { CenterBox } from '@common/Box';
import { UpCaret } from '@common/Icons';
import { useEffect, useState } from 'react';
import styled from 'styled-components';

const Container = styled(CenterBox)<{ isHidden?: boolean }>`
  background-color: var(--scrollup__bg-color);
  border-radius: 50%;
  bottom: 1.5rem;
  cursor: pointer;
  height: 3rem;
  opacity: 0.9;
  position: fixed;
  right: 1.5rem;
  transform: ${({ isHidden }) => isHidden && 'translateY(6rem)'};
  transition: transform 0.15s ease-in-out;
  width: 3rem;
`;

function ScrollUp() {
  const [isHidden, setIsHidden] = useState(true);

  /* -- Hooks -- */
  useEffect(() => {
    const callback = () => {
      if (window.scrollY !== 0) {
        setIsHidden(false);
      } else {
        setIsHidden(true);
      }
    };

    document.addEventListener('scroll', callback);

    return () => document.removeEventListener('scroll', callback);
  }, []);

  /* -- Event Handlers -- */
  const handleClick = () => {
    window.scrollTo({
      behavior: 'smooth',
      top: 0,
    });
  };

  return (
    <Container data-testid="scroll-up" isHidden={isHidden} onClick={handleClick}>
      <UpCaret />
    </Container>
  );
}

export default ScrollUp;

// src/lib/components/ScrollUp.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import cx from '$lib/utils/cx';
	import UpCaret from './icons/UpCaret.svelte';

	/* -- Props & Vars -- */
	let currentPosition = 0;
	let isHidden = true;

	/* -- Lifecycle -- */
	onMount(() => {
		function callback() {
			if (window.scrollY === 0 || window.scrollY > currentPosition) {
				isHidden = true;
			} else {
				isHidden = false;
			}

			currentPosition = window.scrollY;
		}

		document.addEventListener('scroll', callback, { passive: true });

		return () => document.removeEventListener('scroll', callback);
	});

	/* -- Event Handlers -- */
	function handleClick() {
		window.scrollTo({
			behavior: 'smooth',
			top: 0,
		});
	}

	/* -- Rendering -- */
	$: classes = cx('container', isHidden && 'hide');
</script>

<button class={classes} on:click={handleClick}>
	<UpCaret />
</button>

<style>
	.container {
		align-items: center;
		background-color: var(--neutral500);
		border-radius: 50%;
		bottom: 1.5rem;
		color: var(--neutral100);
		cursor: pointer;
		display: flex;
		height: 3rem;
		justify-content: center;
		opacity: 0.9;
		position: fixed;
		right: 1.5rem;
		transition: transform 0.4s var(--easing1);
		width: 3rem;
	}

	.hide {
		transform: translateY(6rem);
	}
</style>
